// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  projectId: "postcraft-ajtjy",
  appId: "1:911757771007:web:c725a1c7d3e7b9c3e04cca",
  storageBucket: "postcraft-ajtjy.firebasestorage.app",
  apiKey: "AIzaSyBzQAGbt4_ivlqyF78MSvLpzJdWceJK92Y",
  authDomain: "postcraft-ajtjy.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "911757771007"
};
